### ISSUE TITLE
Add a dark mode to table reports

### ISSUE THREAD

**Issue by rouk1** [skrub-data/skrub#1165]
### Problem Description

Table report only has a light theme.

### Feature Description

The implementation could be in three parts:

- extract all colors to css variables
- use the created variables everywhere
- create a new set of variables (a dark theme), for a first round dark mode could be current color with inverted luminance
- use a media query to switch between variables sets

Implementation could look like:

```css
@media (prefers-color-scheme: dark) {
  :host {
    /* backgrounds */
    --color-background-primary: #1a1a1a;
    --color-background-secondary: #222;
    --color-background-plots: #121212;

    /* text */
    --color-text-primary: #fff;
    --color-text-secondary: #a2a2a2;

    /* shadow */
    --color-shadow: rgb(0 0 0/58%);
  }
}

@media (prefers-color-scheme: light) {
  :host {
    /* backgrounds */
    --color-background-primary: #fff;
    --color-background-secondary: #fafafb;
    --color-background-plots: #fdfdfd;

    /* text */
    --color-text-primary: #2f3037;
    --color-text-secondary: #616271;

    /* shadow */
    --color-shadow: rgb(0 0 0/19%);
  }
}
```

> [!NOTE]  
> Naming css variables is always tricky, my proposal is to use a consistent pattern: --what-where-variation-interactivity
> `what` could be colors for now but may scale to sizes
> `where` defines in which css rules the variable should be used (background for background, text for font color, ...)
> `variation` values may be variable according to context a title may not have exactly the same color as a subtitle for example
> `interactivity` value on hover for example
